### ISSUE TITLE
Class-specific basic color term dataset

### ISSUE THREAD

**Issue by alexrame** [yulu0724/AttentionColorName#1]
Thanks for the dataset. I can see that you have open sourced what you call the "Domain-specific color name dataset".
Do you have any plan to release the "Class-specific basic color term dataset" ? I would like to reproduce your paper on the Ebay Dataset but I do not have labelised data.

**Comment by yulu0724** [comment]
Hi, thanks for your interest. So far we haven't released the "class-specific basic color term dataset" yet.  I will consider to release it soon. Actually you can collect the dataset from google chrome very easily, just use the query "color name + objects" to obtain the images as many as you want.
